# Generated by Django 4.1.2 on 2022-10-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(auto_now=True)),
                ('order_name', models.CharField(max_length=200)),
                ('order_phone', models.CharField(max_length=200)),
            ],
        ),
    ]
